// Code generated by Kitex v0.4.4. DO NOT EDIT.

package feedsrv

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	feed "github.com/wt993638658/simpletk/kitex_gen/feed"
)

func serviceInfo() *kitex.ServiceInfo {
	return feedSrvServiceInfo
}

var feedSrvServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "FeedSrv"
	handlerType := (*feed.FeedSrv)(nil)
	methods := map[string]kitex.MethodInfo{
		"GetUserFeed":  kitex.NewMethodInfo(getUserFeedHandler, newFeedSrvGetUserFeedArgs, newFeedSrvGetUserFeedResult, false),
		"GetVideoById": kitex.NewMethodInfo(getVideoByIdHandler, newFeedSrvGetVideoByIdArgs, newFeedSrvGetVideoByIdResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "feed",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func getUserFeedHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*feed.FeedSrvGetUserFeedArgs)
	realResult := result.(*feed.FeedSrvGetUserFeedResult)
	success, err := handler.(feed.FeedSrv).GetUserFeed(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFeedSrvGetUserFeedArgs() interface{} {
	return feed.NewFeedSrvGetUserFeedArgs()
}

func newFeedSrvGetUserFeedResult() interface{} {
	return feed.NewFeedSrvGetUserFeedResult()
}

func getVideoByIdHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*feed.FeedSrvGetVideoByIdArgs)
	realResult := result.(*feed.FeedSrvGetVideoByIdResult)
	success, err := handler.(feed.FeedSrv).GetVideoById(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFeedSrvGetVideoByIdArgs() interface{} {
	return feed.NewFeedSrvGetVideoByIdArgs()
}

func newFeedSrvGetVideoByIdResult() interface{} {
	return feed.NewFeedSrvGetVideoByIdResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetUserFeed(ctx context.Context, req *feed.DouyinFeedRequest) (r *feed.DouyinFeedResponse, err error) {
	var _args feed.FeedSrvGetUserFeedArgs
	_args.Req = req
	var _result feed.FeedSrvGetUserFeedResult
	if err = p.c.Call(ctx, "GetUserFeed", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetVideoById(ctx context.Context, req *feed.VideoIdRequest) (r *feed.Video, err error) {
	var _args feed.FeedSrvGetVideoByIdArgs
	_args.Req = req
	var _result feed.FeedSrvGetVideoByIdResult
	if err = p.c.Call(ctx, "GetVideoById", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
